project:
  type: website
  output-dir: docs

website:
  favicon: figures/chestnut_2.png #tree_logo_colors.png
  #title: "Kristin Art"
  navbar:
    title: false # change this to false!
    logo: figures/chestnut_2.png #tree_logo_colors.png #chestnut or chestnut_2
    logo-alt: "Kristin Art"
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      # - href: portfolio.qmd
      #   text: Portfolio
      - href: posts.qmd
        text: Projects
      - href: figures/Art_Kristin_Resume_01212024.pdf
        text: Resume
    
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/kristin-art-29758a224/
      - icon: github
        href: https://github.com/kristinart
      - icon: envelope
        href: mailto:kristinart21@gmail.com
        
    page-footer: 
      left: 
        - "Copyright 2023, Kristin Art"

format:
  html:
    theme: 
      - styles.scss
    css: styles.css
    toc: true
    page-layout: full