project:
  type: website
  output-dir: docs

website:
  #favicon: figures/chestnut_2.png
  title: "Kristin Art"
  navbar:
    title: false # change this to false!
    logo: figures/chestnut_2.png #chestnut or chestnut_2
    logo-alt: "Kristin Art"
    background: primary
    right:
      - href: index.qmd
        text: Home
      # - href: portfolio.qmd
      #   text: Portfolio
      - href: posts.qmd
        text: Projects
      - about.qmd
      - href: figures/Art_Kristin_Resume_07092023.pdf
        text: CV

format:
  html:
    theme: 
      - styles.scss
    css: styles.css
    toc: true
    page-layout: full